version: '3'

services:
  ws-server-package:
    build:
      context: ./ws-server-package
      dockerfile: ./Dockerfile
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      # allowing you to modify the code without having to rebuild the image.
      - ./ws-server-package:/app
      # Just specify a path and let the Engine create a volume.
      # Data present in the base image at the specified mount point will be copied
      # over to the new volume upon volume initialization.
      # node_modules from this new volume will be used and not from your local dev env.
      - /app/node_modules/

    # Expose ports [HOST:CONTAINER}
    ports:
      - "4040:4040"

    # Set environment variables from this file
    env_file:
      - ./ws-server-package/.env

    # Overwrite any env var defined in .env file (if required)
    environment:
      - DEBUG=ws-server-package:*

    # Link to containers in another service.
    # Links also express dependency between services in the same way as depends_on,
    # so they determine the order of service startup.

  ws-client-package:
    build:
      context: ./ws-client-package
      dockerfile: ./Dockerfile
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      # allowing you to modify the code without having to rebuild the image.
      - ./ws-client-package:/app
      # Just specify a path and let the Engine create a volume.
      # Data present in the base image at the specified mount point will be copied
      # over to the new volume upon volume initialization.
      # node_modules from this new volume will be used and not from your local dev env.
      - /app/node_modules/

    # Expose ports [HOST:CONTAINER}
    ports:
      - "3000:3000"

  ws-nginx-package:
    restart: always
    image: ws-nginx-package:latest
    container_name: ws-nginx-package
    build:
      context: ./ws-client-package
      dockerfile: ./Dockerfile.nginx.dev
    volumes:
      - ./ws-client-package/etc/nginx:/etc/nginx/
      - ./ws-client-package/dist:/app
    links:
      - "ws-server-package"
      - "ws-client-package"
    ports:
      - "80:80"